// Code generated by protoc-gen-go. DO NOT EDIT.
// source: log.proto

package stats

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Event struct {
	SpinnakerInstance    *SpinnakerInstance `protobuf:"bytes,1,opt,name=spinnaker_instance,json=spinnakerInstance,proto3" json:"spinnaker_instance,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetSpinnakerInstance() *SpinnakerInstance {
	if m != nil {
		return m.SpinnakerInstance
	}
	return nil
}

type SpinnakerInstance struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Application          *Application `protobuf:"bytes,2,opt,name=application,proto3" json:"application,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SpinnakerInstance) Reset()         { *m = SpinnakerInstance{} }
func (m *SpinnakerInstance) String() string { return proto.CompactTextString(m) }
func (*SpinnakerInstance) ProtoMessage()    {}
func (*SpinnakerInstance) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{1}
}

func (m *SpinnakerInstance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpinnakerInstance.Unmarshal(m, b)
}
func (m *SpinnakerInstance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpinnakerInstance.Marshal(b, m, deterministic)
}
func (m *SpinnakerInstance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpinnakerInstance.Merge(m, src)
}
func (m *SpinnakerInstance) XXX_Size() int {
	return xxx_messageInfo_SpinnakerInstance.Size(m)
}
func (m *SpinnakerInstance) XXX_DiscardUnknown() {
	xxx_messageInfo_SpinnakerInstance.DiscardUnknown(m)
}

var xxx_messageInfo_SpinnakerInstance proto.InternalMessageInfo

func (m *SpinnakerInstance) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SpinnakerInstance) GetApplication() *Application {
	if m != nil {
		return m.Application
	}
	return nil
}

type Application struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Pipeline             *Pipeline `protobuf:"bytes,2,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Application) Reset()         { *m = Application{} }
func (m *Application) String() string { return proto.CompactTextString(m) }
func (*Application) ProtoMessage()    {}
func (*Application) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{2}
}

func (m *Application) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Application.Unmarshal(m, b)
}
func (m *Application) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Application.Marshal(b, m, deterministic)
}
func (m *Application) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Application.Merge(m, src)
}
func (m *Application) XXX_Size() int {
	return xxx_messageInfo_Application.Size(m)
}
func (m *Application) XXX_DiscardUnknown() {
	xxx_messageInfo_Application.DiscardUnknown(m)
}

var xxx_messageInfo_Application proto.InternalMessageInfo

func (m *Application) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Application) GetPipeline() *Pipeline {
	if m != nil {
		return m.Pipeline
	}
	return nil
}

type Pipeline struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Stages               []*Stage `protobuf:"bytes,2,rep,name=stages,proto3" json:"stages,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pipeline) Reset()         { *m = Pipeline{} }
func (m *Pipeline) String() string { return proto.CompactTextString(m) }
func (*Pipeline) ProtoMessage()    {}
func (*Pipeline) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{3}
}

func (m *Pipeline) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pipeline.Unmarshal(m, b)
}
func (m *Pipeline) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pipeline.Marshal(b, m, deterministic)
}
func (m *Pipeline) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pipeline.Merge(m, src)
}
func (m *Pipeline) XXX_Size() int {
	return xxx_messageInfo_Pipeline.Size(m)
}
func (m *Pipeline) XXX_DiscardUnknown() {
	xxx_messageInfo_Pipeline.DiscardUnknown(m)
}

var xxx_messageInfo_Pipeline proto.InternalMessageInfo

func (m *Pipeline) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Pipeline) GetStages() []*Stage {
	if m != nil {
		return m.Stages
	}
	return nil
}

type Stage struct {
	Id                   string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CloudProvider        *CloudProvider `protobuf:"bytes,2,opt,name=cloud_provider,json=cloudProvider,proto3" json:"cloud_provider,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Stage) Reset()         { *m = Stage{} }
func (m *Stage) String() string { return proto.CompactTextString(m) }
func (*Stage) ProtoMessage()    {}
func (*Stage) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{4}
}

func (m *Stage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stage.Unmarshal(m, b)
}
func (m *Stage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stage.Marshal(b, m, deterministic)
}
func (m *Stage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stage.Merge(m, src)
}
func (m *Stage) XXX_Size() int {
	return xxx_messageInfo_Stage.Size(m)
}
func (m *Stage) XXX_DiscardUnknown() {
	xxx_messageInfo_Stage.DiscardUnknown(m)
}

var xxx_messageInfo_Stage proto.InternalMessageInfo

func (m *Stage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Stage) GetCloudProvider() *CloudProvider {
	if m != nil {
		return m.CloudProvider
	}
	return nil
}

type CloudProvider struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloudProvider) Reset()         { *m = CloudProvider{} }
func (m *CloudProvider) String() string { return proto.CompactTextString(m) }
func (*CloudProvider) ProtoMessage()    {}
func (*CloudProvider) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{5}
}

func (m *CloudProvider) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloudProvider.Unmarshal(m, b)
}
func (m *CloudProvider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloudProvider.Marshal(b, m, deterministic)
}
func (m *CloudProvider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloudProvider.Merge(m, src)
}
func (m *CloudProvider) XXX_Size() int {
	return xxx_messageInfo_CloudProvider.Size(m)
}
func (m *CloudProvider) XXX_DiscardUnknown() {
	xxx_messageInfo_CloudProvider.DiscardUnknown(m)
}

var xxx_messageInfo_CloudProvider proto.InternalMessageInfo

func (m *CloudProvider) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*Event)(nil), "io.spinnaker.stats.v1.Event")
	proto.RegisterType((*SpinnakerInstance)(nil), "io.spinnaker.stats.v1.SpinnakerInstance")
	proto.RegisterType((*Application)(nil), "io.spinnaker.stats.v1.Application")
	proto.RegisterType((*Pipeline)(nil), "io.spinnaker.stats.v1.Pipeline")
	proto.RegisterType((*Stage)(nil), "io.spinnaker.stats.v1.Stage")
	proto.RegisterType((*CloudProvider)(nil), "io.spinnaker.stats.v1.CloudProvider")
}

func init() { proto.RegisterFile("log.proto", fileDescriptor_a153da538f858886) }

var fileDescriptor_a153da538f858886 = []byte{
	// 269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xcf, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0x59, 0xa5, 0x73, 0x7b, 0x65, 0x83, 0x05, 0x84, 0x1e, 0x84, 0x8d, 0xe0, 0xa1, 0xa7,
	0x80, 0xd3, 0x9b, 0x27, 0x7f, 0x1d, 0xc4, 0x4b, 0x89, 0x07, 0x61, 0x97, 0x19, 0x9b, 0x30, 0x1e,
	0x96, 0x24, 0x34, 0xb1, 0x7f, 0xbf, 0x2c, 0x64, 0xb3, 0xae, 0xf6, 0x98, 0xef, 0xfb, 0xbc, 0xef,
	0x27, 0x84, 0xc0, 0xb4, 0x36, 0x3b, 0x66, 0x1b, 0xe3, 0x0d, 0xb9, 0x40, 0xc3, 0x9c, 0x45, 0xad,
	0xc5, 0x97, 0x6a, 0x98, 0xf3, 0xc2, 0x3b, 0xd6, 0x5e, 0xd3, 0x0f, 0x48, 0x9f, 0x5b, 0xa5, 0x3d,
	0x79, 0x07, 0x72, 0x1c, 0x6f, 0x51, 0x3b, 0x2f, 0x74, 0xa5, 0xf2, 0xd1, 0x6a, 0x54, 0x64, 0xeb,
	0x82, 0xfd, 0xbb, 0xcc, 0xde, 0x0e, 0xd1, 0x4b, 0xe4, 0xf9, 0xc2, 0x9d, 0x46, 0x14, 0x61, 0xd1,
	0xe3, 0xc8, 0x1c, 0x12, 0x94, 0xa1, 0x7d, 0xca, 0x13, 0x94, 0xe4, 0x09, 0x32, 0x61, 0x6d, 0x8d,
	0x95, 0xf0, 0x68, 0x74, 0x9e, 0x04, 0x2d, 0x1d, 0xd0, 0xde, 0xff, 0x92, 0xbc, 0xbb, 0x46, 0x37,
	0x90, 0x75, 0x66, 0x3d, 0xc9, 0x1d, 0x4c, 0x2c, 0x5a, 0x55, 0xa3, 0x56, 0xd1, 0xb0, 0x1c, 0x30,
	0x94, 0x11, 0xe3, 0xc7, 0x05, 0x5a, 0xc2, 0xe4, 0x90, 0xf6, 0x8a, 0x6f, 0x61, 0xec, 0xbc, 0xd8,
	0x29, 0x97, 0x27, 0xab, 0xb3, 0x22, 0x5b, 0x5f, 0x0e, 0xbd, 0xd7, 0x1e, 0xe2, 0x91, 0xa5, 0x12,
	0xd2, 0x10, 0xf4, 0xea, 0x5e, 0x61, 0x5e, 0xd5, 0xe6, 0x5b, 0x6e, 0x6d, 0x63, 0x5a, 0x94, 0xaa,
	0x89, 0xb7, 0xbd, 0x1a, 0xa8, 0x7d, 0xdc, 0xc3, 0x65, 0x64, 0xf9, 0xac, 0xea, 0x1e, 0xe9, 0x12,
	0x66, 0x7f, 0xe6, 0xa7, 0xb6, 0x87, 0xf3, 0x4d, 0x1a, 0x9a, 0x3e, 0xc7, 0xe1, 0xa3, 0xdc, 0xfc,
	0x04, 0x00, 0x00, 0xff, 0xff, 0x46, 0xe1, 0xd2, 0x99, 0x35, 0x02, 0x00, 0x00,
}
