// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stats/log.proto

package stats

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Sourced from https://github.com/spinnaker/orca/blob/master/orca-core/src/main/java/com/netflix/spinnaker/orca/ExecutionStatus.java
type Status int32

const (
	Status_UNKNOWN         Status = 0
	Status_NOT_STARTED     Status = 1
	Status_RUNNING         Status = 2
	Status_PAUSED          Status = 3
	Status_SUSPENDED       Status = 4
	Status_SUCCEEDED       Status = 5
	Status_FAILED_CONTINUE Status = 6
	Status_TERMINAL        Status = 7
	Status_CANCELED        Status = 8
	Status_REDIRECT        Status = 9
	Status_STOPPED         Status = 10
	Status_SKIPPED         Status = 11
	Status_BUFFERED        Status = 12
)

var Status_name = map[int32]string{
	0:  "UNKNOWN",
	1:  "NOT_STARTED",
	2:  "RUNNING",
	3:  "PAUSED",
	4:  "SUSPENDED",
	5:  "SUCCEEDED",
	6:  "FAILED_CONTINUE",
	7:  "TERMINAL",
	8:  "CANCELED",
	9:  "REDIRECT",
	10: "STOPPED",
	11: "SKIPPED",
	12: "BUFFERED",
}

var Status_value = map[string]int32{
	"UNKNOWN":         0,
	"NOT_STARTED":     1,
	"RUNNING":         2,
	"PAUSED":          3,
	"SUSPENDED":       4,
	"SUCCEEDED":       5,
	"FAILED_CONTINUE": 6,
	"TERMINAL":        7,
	"CANCELED":        8,
	"REDIRECT":        9,
	"STOPPED":         10,
	"SKIPPED":         11,
	"BUFFERED":        12,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_be815d6cfeb20831, []int{0}
}

type Pipeline_Type int32

const (
	Pipeline_UNKNOWN             Pipeline_Type = 0
	Pipeline_STANDARD            Pipeline_Type = 1
	Pipeline_MANAGED_TEMPLATE_V1 Pipeline_Type = 2
	Pipeline_MANAGED_TEMPLATE_V2 Pipeline_Type = 3
)

var Pipeline_Type_name = map[int32]string{
	0: "UNKNOWN",
	1: "STANDARD",
	2: "MANAGED_TEMPLATE_V1",
	3: "MANAGED_TEMPLATE_V2",
}

var Pipeline_Type_value = map[string]int32{
	"UNKNOWN":             0,
	"STANDARD":            1,
	"MANAGED_TEMPLATE_V1": 2,
	"MANAGED_TEMPLATE_V2": 3,
}

func (x Pipeline_Type) String() string {
	return proto.EnumName(Pipeline_Type_name, int32(x))
}

func (Pipeline_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_be815d6cfeb20831, []int{3, 0}
}

// Sourced from https://github.com/spinnaker/echo/tree/master/echo-model/src/main/java/com/netflix/spinnaker/echo/model/trigger
type Pipeline_Trigger_Type int32

const (
	Pipeline_Trigger_UNKNOWN     Pipeline_Trigger_Type = 0
	Pipeline_Trigger_ARTIFACTORY Pipeline_Trigger_Type = 1
	Pipeline_Trigger_BUILD       Pipeline_Trigger_Type = 2
	Pipeline_Trigger_DOCKER      Pipeline_Trigger_Type = 3
	Pipeline_Trigger_GIT         Pipeline_Trigger_Type = 4
	Pipeline_Trigger_MANUAL      Pipeline_Trigger_Type = 5
	Pipeline_Trigger_PUBSUB      Pipeline_Trigger_Type = 6
	Pipeline_Trigger_WEBHOOK     Pipeline_Trigger_Type = 7
)

var Pipeline_Trigger_Type_name = map[int32]string{
	0: "UNKNOWN",
	1: "ARTIFACTORY",
	2: "BUILD",
	3: "DOCKER",
	4: "GIT",
	5: "MANUAL",
	6: "PUBSUB",
	7: "WEBHOOK",
}

var Pipeline_Trigger_Type_value = map[string]int32{
	"UNKNOWN":     0,
	"ARTIFACTORY": 1,
	"BUILD":       2,
	"DOCKER":      3,
	"GIT":         4,
	"MANUAL":      5,
	"PUBSUB":      6,
	"WEBHOOK":     7,
}

func (x Pipeline_Trigger_Type) String() string {
	return proto.EnumName(Pipeline_Trigger_Type_name, int32(x))
}

func (Pipeline_Trigger_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_be815d6cfeb20831, []int{3, 0, 0}
}

type Event struct {
	SpinnakerInstance    *SpinnakerInstance `protobuf:"bytes,1,opt,name=spinnaker_instance,json=spinnakerInstance,proto3" json:"spinnaker_instance,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_be815d6cfeb20831, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetSpinnakerInstance() *SpinnakerInstance {
	if m != nil {
		return m.SpinnakerInstance
	}
	return nil
}

type SpinnakerInstance struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version              string       `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Application          *Application `protobuf:"bytes,3,opt,name=application,proto3" json:"application,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SpinnakerInstance) Reset()         { *m = SpinnakerInstance{} }
func (m *SpinnakerInstance) String() string { return proto.CompactTextString(m) }
func (*SpinnakerInstance) ProtoMessage()    {}
func (*SpinnakerInstance) Descriptor() ([]byte, []int) {
	return fileDescriptor_be815d6cfeb20831, []int{1}
}

func (m *SpinnakerInstance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpinnakerInstance.Unmarshal(m, b)
}
func (m *SpinnakerInstance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpinnakerInstance.Marshal(b, m, deterministic)
}
func (m *SpinnakerInstance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpinnakerInstance.Merge(m, src)
}
func (m *SpinnakerInstance) XXX_Size() int {
	return xxx_messageInfo_SpinnakerInstance.Size(m)
}
func (m *SpinnakerInstance) XXX_DiscardUnknown() {
	xxx_messageInfo_SpinnakerInstance.DiscardUnknown(m)
}

var xxx_messageInfo_SpinnakerInstance proto.InternalMessageInfo

func (m *SpinnakerInstance) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SpinnakerInstance) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *SpinnakerInstance) GetApplication() *Application {
	if m != nil {
		return m.Application
	}
	return nil
}

type Application struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Pipeline             *Pipeline `protobuf:"bytes,2,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Application) Reset()         { *m = Application{} }
func (m *Application) String() string { return proto.CompactTextString(m) }
func (*Application) ProtoMessage()    {}
func (*Application) Descriptor() ([]byte, []int) {
	return fileDescriptor_be815d6cfeb20831, []int{2}
}

func (m *Application) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Application.Unmarshal(m, b)
}
func (m *Application) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Application.Marshal(b, m, deterministic)
}
func (m *Application) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Application.Merge(m, src)
}
func (m *Application) XXX_Size() int {
	return xxx_messageInfo_Application.Size(m)
}
func (m *Application) XXX_DiscardUnknown() {
	xxx_messageInfo_Application.DiscardUnknown(m)
}

var xxx_messageInfo_Application proto.InternalMessageInfo

func (m *Application) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Application) GetPipeline() *Pipeline {
	if m != nil {
		return m.Pipeline
	}
	return nil
}

type Pipeline struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 Pipeline_Type     `protobuf:"varint,2,opt,name=type,proto3,enum=io.spinnaker.protos.stats.Pipeline_Type" json:"type,omitempty"`
	Trigger              *Pipeline_Trigger `protobuf:"bytes,3,opt,name=trigger,proto3" json:"trigger,omitempty"`
	Stages               []*Stage          `protobuf:"bytes,4,rep,name=stages,proto3" json:"stages,omitempty"`
	Status               Status            `protobuf:"varint,5,opt,name=status,proto3,enum=io.spinnaker.protos.stats.Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Pipeline) Reset()         { *m = Pipeline{} }
func (m *Pipeline) String() string { return proto.CompactTextString(m) }
func (*Pipeline) ProtoMessage()    {}
func (*Pipeline) Descriptor() ([]byte, []int) {
	return fileDescriptor_be815d6cfeb20831, []int{3}
}

func (m *Pipeline) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pipeline.Unmarshal(m, b)
}
func (m *Pipeline) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pipeline.Marshal(b, m, deterministic)
}
func (m *Pipeline) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pipeline.Merge(m, src)
}
func (m *Pipeline) XXX_Size() int {
	return xxx_messageInfo_Pipeline.Size(m)
}
func (m *Pipeline) XXX_DiscardUnknown() {
	xxx_messageInfo_Pipeline.DiscardUnknown(m)
}

var xxx_messageInfo_Pipeline proto.InternalMessageInfo

func (m *Pipeline) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Pipeline) GetType() Pipeline_Type {
	if m != nil {
		return m.Type
	}
	return Pipeline_UNKNOWN
}

func (m *Pipeline) GetTrigger() *Pipeline_Trigger {
	if m != nil {
		return m.Trigger
	}
	return nil
}

func (m *Pipeline) GetStages() []*Stage {
	if m != nil {
		return m.Stages
	}
	return nil
}

func (m *Pipeline) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_UNKNOWN
}

type Pipeline_Trigger struct {
	Type                 Pipeline_Trigger_Type `protobuf:"varint,1,opt,name=type,proto3,enum=io.spinnaker.protos.stats.Pipeline_Trigger_Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Pipeline_Trigger) Reset()         { *m = Pipeline_Trigger{} }
func (m *Pipeline_Trigger) String() string { return proto.CompactTextString(m) }
func (*Pipeline_Trigger) ProtoMessage()    {}
func (*Pipeline_Trigger) Descriptor() ([]byte, []int) {
	return fileDescriptor_be815d6cfeb20831, []int{3, 0}
}

func (m *Pipeline_Trigger) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pipeline_Trigger.Unmarshal(m, b)
}
func (m *Pipeline_Trigger) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pipeline_Trigger.Marshal(b, m, deterministic)
}
func (m *Pipeline_Trigger) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pipeline_Trigger.Merge(m, src)
}
func (m *Pipeline_Trigger) XXX_Size() int {
	return xxx_messageInfo_Pipeline_Trigger.Size(m)
}
func (m *Pipeline_Trigger) XXX_DiscardUnknown() {
	xxx_messageInfo_Pipeline_Trigger.DiscardUnknown(m)
}

var xxx_messageInfo_Pipeline_Trigger proto.InternalMessageInfo

func (m *Pipeline_Trigger) GetType() Pipeline_Trigger_Type {
	if m != nil {
		return m.Type
	}
	return Pipeline_Trigger_UNKNOWN
}

type Stage struct {
	Id                   string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               Status         `protobuf:"varint,2,opt,name=status,proto3,enum=io.spinnaker.protos.stats.Status" json:"status,omitempty"`
	CloudProvider        *CloudProvider `protobuf:"bytes,3,opt,name=cloud_provider,json=cloudProvider,proto3" json:"cloud_provider,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Stage) Reset()         { *m = Stage{} }
func (m *Stage) String() string { return proto.CompactTextString(m) }
func (*Stage) ProtoMessage()    {}
func (*Stage) Descriptor() ([]byte, []int) {
	return fileDescriptor_be815d6cfeb20831, []int{4}
}

func (m *Stage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stage.Unmarshal(m, b)
}
func (m *Stage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stage.Marshal(b, m, deterministic)
}
func (m *Stage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stage.Merge(m, src)
}
func (m *Stage) XXX_Size() int {
	return xxx_messageInfo_Stage.Size(m)
}
func (m *Stage) XXX_DiscardUnknown() {
	xxx_messageInfo_Stage.DiscardUnknown(m)
}

var xxx_messageInfo_Stage proto.InternalMessageInfo

func (m *Stage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Stage) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_UNKNOWN
}

func (m *Stage) GetCloudProvider() *CloudProvider {
	if m != nil {
		return m.CloudProvider
	}
	return nil
}

type CloudProvider struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloudProvider) Reset()         { *m = CloudProvider{} }
func (m *CloudProvider) String() string { return proto.CompactTextString(m) }
func (*CloudProvider) ProtoMessage()    {}
func (*CloudProvider) Descriptor() ([]byte, []int) {
	return fileDescriptor_be815d6cfeb20831, []int{5}
}

func (m *CloudProvider) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloudProvider.Unmarshal(m, b)
}
func (m *CloudProvider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloudProvider.Marshal(b, m, deterministic)
}
func (m *CloudProvider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloudProvider.Merge(m, src)
}
func (m *CloudProvider) XXX_Size() int {
	return xxx_messageInfo_CloudProvider.Size(m)
}
func (m *CloudProvider) XXX_DiscardUnknown() {
	xxx_messageInfo_CloudProvider.DiscardUnknown(m)
}

var xxx_messageInfo_CloudProvider proto.InternalMessageInfo

func (m *CloudProvider) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterEnum("io.spinnaker.protos.stats.Status", Status_name, Status_value)
	proto.RegisterEnum("io.spinnaker.protos.stats.Pipeline_Type", Pipeline_Type_name, Pipeline_Type_value)
	proto.RegisterEnum("io.spinnaker.protos.stats.Pipeline_Trigger_Type", Pipeline_Trigger_Type_name, Pipeline_Trigger_Type_value)
	proto.RegisterType((*Event)(nil), "io.spinnaker.protos.stats.Event")
	proto.RegisterType((*SpinnakerInstance)(nil), "io.spinnaker.protos.stats.SpinnakerInstance")
	proto.RegisterType((*Application)(nil), "io.spinnaker.protos.stats.Application")
	proto.RegisterType((*Pipeline)(nil), "io.spinnaker.protos.stats.Pipeline")
	proto.RegisterType((*Pipeline_Trigger)(nil), "io.spinnaker.protos.stats.Pipeline.Trigger")
	proto.RegisterType((*Stage)(nil), "io.spinnaker.protos.stats.Stage")
	proto.RegisterType((*CloudProvider)(nil), "io.spinnaker.protos.stats.CloudProvider")
}

func init() { proto.RegisterFile("stats/log.proto", fileDescriptor_be815d6cfeb20831) }

var fileDescriptor_be815d6cfeb20831 = []byte{
	// 647 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xdd, 0x6e, 0xd3, 0x4a,
	0x18, 0x3c, 0xce, 0x9f, 0x93, 0xcf, 0xfd, 0xd9, 0x6e, 0x2f, 0x4e, 0xce, 0xb9, 0x21, 0x18, 0x09,
	0x55, 0x80, 0x12, 0x08, 0x37, 0x20, 0x21, 0xa1, 0x8d, 0xbd, 0x69, 0xad, 0x24, 0x6b, 0x6b, 0x6d,
	0x53, 0x01, 0x12, 0x51, 0x9a, 0x58, 0xc1, 0x22, 0xd8, 0x56, 0xec, 0x54, 0xea, 0x13, 0xf0, 0x20,
	0x48, 0x3c, 0x04, 0xd7, 0x3c, 0x18, 0xda, 0x8d, 0x93, 0x86, 0xa6, 0x44, 0xed, 0x9d, 0xe7, 0xdb,
	0x99, 0xf9, 0xc6, 0xb3, 0x0b, 0x87, 0x69, 0x36, 0xca, 0xd2, 0xd6, 0x2c, 0x9e, 0x36, 0x93, 0x79,
	0x9c, 0xc5, 0xf8, 0xbf, 0x30, 0x6e, 0xa6, 0x49, 0x18, 0x45, 0xa3, 0x2f, 0xc1, 0x7c, 0x39, 0x4b,
	0x9b, 0x92, 0xa4, 0x4f, 0xa0, 0x4c, 0x2f, 0x83, 0x28, 0xc3, 0x1f, 0x01, 0xaf, 0x29, 0xc3, 0x30,
	0x4a, 0xb3, 0x51, 0x34, 0x0e, 0xea, 0x4a, 0x43, 0x39, 0xd1, 0xda, 0xcf, 0x9a, 0x7f, 0x35, 0x68,
	0xba, 0xab, 0xb1, 0x95, 0x6b, 0xf8, 0x51, 0x7a, 0x73, 0xa4, 0x7f, 0x53, 0xe0, 0x68, 0x8b, 0x88,
	0x0f, 0xa0, 0x10, 0x4e, 0xe4, 0x8a, 0x1a, 0x2f, 0x84, 0x13, 0x5c, 0x07, 0xf5, 0x32, 0x98, 0xa7,
	0x61, 0x1c, 0xd5, 0x0b, 0x72, 0xb8, 0x82, 0xf8, 0x0c, 0xb4, 0x51, 0x92, 0xcc, 0xc2, 0xf1, 0x28,
	0x13, 0xa7, 0x45, 0x99, 0xea, 0xf1, 0x8e, 0x54, 0xe4, 0x9a, 0xcd, 0x37, 0xa5, 0xfa, 0x27, 0xd0,
	0x36, 0xce, 0xb6, 0x22, 0xbc, 0x85, 0x6a, 0x12, 0x26, 0xc1, 0x2c, 0x8c, 0x02, 0x99, 0x41, 0x6b,
	0x3f, 0xda, 0xb1, 0xc5, 0xc9, 0xa9, 0x7c, 0x2d, 0xd2, 0x7f, 0x94, 0xa0, 0xba, 0x1a, 0x6f, 0xb9,
	0xbf, 0x81, 0x52, 0x76, 0x95, 0x2c, 0x9d, 0x0f, 0xda, 0x27, 0x77, 0x70, 0x6e, 0x7a, 0x57, 0x49,
	0xc0, 0xa5, 0x0a, 0x53, 0x50, 0xb3, 0x79, 0x38, 0x9d, 0x06, 0xf3, 0xbc, 0x80, 0xa7, 0x77, 0x32,
	0x58, 0x4a, 0xf8, 0x4a, 0x8b, 0x5f, 0x41, 0x25, 0xcd, 0x46, 0xd3, 0x20, 0xad, 0x97, 0x1a, 0xc5,
	0x13, 0xad, 0xdd, 0xd8, 0x75, 0xb9, 0x82, 0xc8, 0x73, 0x3e, 0x7e, 0x2d, 0x95, 0xd9, 0x22, 0xad,
	0x97, 0xe5, 0x0f, 0x3c, 0xdc, 0xad, 0xcc, 0x16, 0x29, 0xcf, 0x05, 0xff, 0xff, 0x54, 0x40, 0xcd,
	0x93, 0x60, 0x33, 0x6f, 0x41, 0x91, 0x26, 0xcf, 0xef, 0xf1, 0x13, 0x1b, 0x6d, 0xe8, 0x21, 0x94,
	0x04, 0xc2, 0x1a, 0xa8, 0x3e, 0xeb, 0x31, 0xfb, 0x9c, 0xa1, 0x7f, 0xf0, 0x21, 0x68, 0x84, 0x7b,
	0x56, 0x97, 0x18, 0x9e, 0xcd, 0xdf, 0x23, 0x05, 0xd7, 0xa0, 0xdc, 0xf1, 0xad, 0xbe, 0x89, 0x0a,
	0x18, 0xa0, 0x62, 0xda, 0x46, 0x8f, 0x72, 0x54, 0xc4, 0x2a, 0x14, 0x4f, 0x2d, 0x0f, 0x95, 0xc4,
	0x70, 0x40, 0x98, 0x4f, 0xfa, 0xa8, 0x2c, 0xbe, 0x1d, 0xbf, 0xe3, 0xfa, 0x1d, 0x54, 0x11, 0xae,
	0xe7, 0xb4, 0x73, 0x66, 0xdb, 0x3d, 0xa4, 0xea, 0xee, 0x6d, 0xab, 0xf6, 0xa0, 0xea, 0x7a, 0x84,
	0x99, 0x84, 0x9b, 0x48, 0xc1, 0xff, 0xc2, 0xf1, 0x80, 0x30, 0x72, 0x4a, 0xcd, 0xa1, 0x47, 0x07,
	0x4e, 0x9f, 0x78, 0x74, 0xf8, 0xee, 0x05, 0x2a, 0xdc, 0x7e, 0xd0, 0x46, 0x45, 0xfd, 0xbb, 0x02,
	0x65, 0x59, 0xef, 0xd6, 0x2b, 0xb9, 0xae, 0xb9, 0x70, 0xcf, 0x9a, 0xb1, 0x0d, 0x07, 0xe3, 0x59,
	0xbc, 0x98, 0x0c, 0x93, 0x79, 0x7c, 0x19, 0x4e, 0xd6, 0x2f, 0x65, 0xd7, 0x53, 0x33, 0x84, 0xc0,
	0xc9, 0xf9, 0x7c, 0x7f, 0xbc, 0x09, 0xf5, 0x07, 0xb0, 0xff, 0xc7, 0xf9, 0xcd, 0xb0, 0x4f, 0x7e,
	0x29, 0x50, 0x59, 0x86, 0xd8, 0xba, 0x09, 0x66, 0x7b, 0x43, 0xd7, 0x23, 0xdc, 0xa3, 0xa2, 0x21,
	0x0d, 0x54, 0xee, 0x33, 0x66, 0xb1, 0xd3, 0xe5, 0x5d, 0x38, 0xc4, 0x77, 0xa9, 0x89, 0x8a, 0x78,
	0x1f, 0x6a, 0xae, 0xef, 0x3a, 0x94, 0x99, 0xd4, 0x44, 0xa5, 0x25, 0x34, 0x0c, 0x4a, 0x05, 0x2c,
	0xe3, 0x63, 0x38, 0xec, 0x12, 0xab, 0x4f, 0xcd, 0xa1, 0x61, 0x33, 0xcf, 0x62, 0x3e, 0x45, 0x15,
	0xd1, 0xbd, 0x47, 0xf9, 0xc0, 0x62, 0xa4, 0x8f, 0x54, 0x81, 0x0c, 0xc2, 0x0c, 0xda, 0xa7, 0x26,
	0xaa, 0x0a, 0xc4, 0xa9, 0x69, 0x71, 0x6a, 0x78, 0xa8, 0x26, 0xb6, 0xba, 0x9e, 0xed, 0x38, 0xd4,
	0x44, 0x20, 0x41, 0xcf, 0x92, 0x40, 0x13, 0xbc, 0x8e, 0xdf, 0xed, 0x52, 0x4e, 0x4d, 0xb4, 0xd7,
	0xd1, 0x3f, 0x34, 0xa6, 0x61, 0xf6, 0x79, 0x71, 0xd1, 0x1c, 0xc7, 0x5f, 0x5b, 0xeb, 0xa6, 0x5a,
	0xb2, 0xa9, 0x96, 0x2c, 0xea, 0xa2, 0x22, 0xc1, 0xcb, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x5e,
	0x55, 0xa4, 0xef, 0x5f, 0x05, 0x00, 0x00,
}
