// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stats/log.proto

package stats

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Yanked from https://github.com/spinnaker/orca/blob/master/orca-core/src/main/java/com/netflix/spinnaker/orca/ExecutionStatus.java
type Status int32

const (
	Status_UNKNOWN         Status = 0
	Status_NOT_STARTED     Status = 1
	Status_RUNNING         Status = 2
	Status_PAUSED          Status = 3
	Status_SUSPENDED       Status = 4
	Status_SUCCEEDED       Status = 5
	Status_FAILED_CONTINUE Status = 6
	Status_TERMINAL        Status = 7
	Status_CANCELED        Status = 8
	Status_REDIRECT        Status = 9
	Status_STOPPED         Status = 10
	Status_SKIPPED         Status = 11
	Status_BUFFERED        Status = 12
)

var Status_name = map[int32]string{
	0:  "UNKNOWN",
	1:  "NOT_STARTED",
	2:  "RUNNING",
	3:  "PAUSED",
	4:  "SUSPENDED",
	5:  "SUCCEEDED",
	6:  "FAILED_CONTINUE",
	7:  "TERMINAL",
	8:  "CANCELED",
	9:  "REDIRECT",
	10: "STOPPED",
	11: "SKIPPED",
	12: "BUFFERED",
}

var Status_value = map[string]int32{
	"UNKNOWN":         0,
	"NOT_STARTED":     1,
	"RUNNING":         2,
	"PAUSED":          3,
	"SUSPENDED":       4,
	"SUCCEEDED":       5,
	"FAILED_CONTINUE": 6,
	"TERMINAL":        7,
	"CANCELED":        8,
	"REDIRECT":        9,
	"STOPPED":         10,
	"SKIPPED":         11,
	"BUFFERED":        12,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_be815d6cfeb20831, []int{0}
}

type Event struct {
	SpinnakerInstance    *SpinnakerInstance `protobuf:"bytes,1,opt,name=spinnaker_instance,json=spinnakerInstance,proto3" json:"spinnaker_instance,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_be815d6cfeb20831, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetSpinnakerInstance() *SpinnakerInstance {
	if m != nil {
		return m.SpinnakerInstance
	}
	return nil
}

type SpinnakerInstance struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Application          *Application `protobuf:"bytes,2,opt,name=application,proto3" json:"application,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SpinnakerInstance) Reset()         { *m = SpinnakerInstance{} }
func (m *SpinnakerInstance) String() string { return proto.CompactTextString(m) }
func (*SpinnakerInstance) ProtoMessage()    {}
func (*SpinnakerInstance) Descriptor() ([]byte, []int) {
	return fileDescriptor_be815d6cfeb20831, []int{1}
}

func (m *SpinnakerInstance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpinnakerInstance.Unmarshal(m, b)
}
func (m *SpinnakerInstance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpinnakerInstance.Marshal(b, m, deterministic)
}
func (m *SpinnakerInstance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpinnakerInstance.Merge(m, src)
}
func (m *SpinnakerInstance) XXX_Size() int {
	return xxx_messageInfo_SpinnakerInstance.Size(m)
}
func (m *SpinnakerInstance) XXX_DiscardUnknown() {
	xxx_messageInfo_SpinnakerInstance.DiscardUnknown(m)
}

var xxx_messageInfo_SpinnakerInstance proto.InternalMessageInfo

func (m *SpinnakerInstance) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SpinnakerInstance) GetApplication() *Application {
	if m != nil {
		return m.Application
	}
	return nil
}

type Application struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Pipeline             *Pipeline `protobuf:"bytes,2,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Application) Reset()         { *m = Application{} }
func (m *Application) String() string { return proto.CompactTextString(m) }
func (*Application) ProtoMessage()    {}
func (*Application) Descriptor() ([]byte, []int) {
	return fileDescriptor_be815d6cfeb20831, []int{2}
}

func (m *Application) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Application.Unmarshal(m, b)
}
func (m *Application) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Application.Marshal(b, m, deterministic)
}
func (m *Application) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Application.Merge(m, src)
}
func (m *Application) XXX_Size() int {
	return xxx_messageInfo_Application.Size(m)
}
func (m *Application) XXX_DiscardUnknown() {
	xxx_messageInfo_Application.DiscardUnknown(m)
}

var xxx_messageInfo_Application proto.InternalMessageInfo

func (m *Application) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Application) GetPipeline() *Pipeline {
	if m != nil {
		return m.Pipeline
	}
	return nil
}

type Pipeline struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               Status   `protobuf:"varint,2,opt,name=status,proto3,enum=io.spinnaker.protos.stats.Status" json:"status,omitempty"`
	Stages               []*Stage `protobuf:"bytes,3,rep,name=stages,proto3" json:"stages,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pipeline) Reset()         { *m = Pipeline{} }
func (m *Pipeline) String() string { return proto.CompactTextString(m) }
func (*Pipeline) ProtoMessage()    {}
func (*Pipeline) Descriptor() ([]byte, []int) {
	return fileDescriptor_be815d6cfeb20831, []int{3}
}

func (m *Pipeline) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pipeline.Unmarshal(m, b)
}
func (m *Pipeline) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pipeline.Marshal(b, m, deterministic)
}
func (m *Pipeline) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pipeline.Merge(m, src)
}
func (m *Pipeline) XXX_Size() int {
	return xxx_messageInfo_Pipeline.Size(m)
}
func (m *Pipeline) XXX_DiscardUnknown() {
	xxx_messageInfo_Pipeline.DiscardUnknown(m)
}

var xxx_messageInfo_Pipeline proto.InternalMessageInfo

func (m *Pipeline) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Pipeline) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_UNKNOWN
}

func (m *Pipeline) GetStages() []*Stage {
	if m != nil {
		return m.Stages
	}
	return nil
}

type Stage struct {
	Id                   string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               Status         `protobuf:"varint,2,opt,name=status,proto3,enum=io.spinnaker.protos.stats.Status" json:"status,omitempty"`
	CloudProvider        *CloudProvider `protobuf:"bytes,3,opt,name=cloud_provider,json=cloudProvider,proto3" json:"cloud_provider,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Stage) Reset()         { *m = Stage{} }
func (m *Stage) String() string { return proto.CompactTextString(m) }
func (*Stage) ProtoMessage()    {}
func (*Stage) Descriptor() ([]byte, []int) {
	return fileDescriptor_be815d6cfeb20831, []int{4}
}

func (m *Stage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stage.Unmarshal(m, b)
}
func (m *Stage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stage.Marshal(b, m, deterministic)
}
func (m *Stage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stage.Merge(m, src)
}
func (m *Stage) XXX_Size() int {
	return xxx_messageInfo_Stage.Size(m)
}
func (m *Stage) XXX_DiscardUnknown() {
	xxx_messageInfo_Stage.DiscardUnknown(m)
}

var xxx_messageInfo_Stage proto.InternalMessageInfo

func (m *Stage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Stage) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_UNKNOWN
}

func (m *Stage) GetCloudProvider() *CloudProvider {
	if m != nil {
		return m.CloudProvider
	}
	return nil
}

type CloudProvider struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloudProvider) Reset()         { *m = CloudProvider{} }
func (m *CloudProvider) String() string { return proto.CompactTextString(m) }
func (*CloudProvider) ProtoMessage()    {}
func (*CloudProvider) Descriptor() ([]byte, []int) {
	return fileDescriptor_be815d6cfeb20831, []int{5}
}

func (m *CloudProvider) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloudProvider.Unmarshal(m, b)
}
func (m *CloudProvider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloudProvider.Marshal(b, m, deterministic)
}
func (m *CloudProvider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloudProvider.Merge(m, src)
}
func (m *CloudProvider) XXX_Size() int {
	return xxx_messageInfo_CloudProvider.Size(m)
}
func (m *CloudProvider) XXX_DiscardUnknown() {
	xxx_messageInfo_CloudProvider.DiscardUnknown(m)
}

var xxx_messageInfo_CloudProvider proto.InternalMessageInfo

func (m *CloudProvider) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterEnum("io.spinnaker.protos.stats.Status", Status_name, Status_value)
	proto.RegisterType((*Event)(nil), "io.spinnaker.protos.stats.Event")
	proto.RegisterType((*SpinnakerInstance)(nil), "io.spinnaker.protos.stats.SpinnakerInstance")
	proto.RegisterType((*Application)(nil), "io.spinnaker.protos.stats.Application")
	proto.RegisterType((*Pipeline)(nil), "io.spinnaker.protos.stats.Pipeline")
	proto.RegisterType((*Stage)(nil), "io.spinnaker.protos.stats.Stage")
	proto.RegisterType((*CloudProvider)(nil), "io.spinnaker.protos.stats.CloudProvider")
}

func init() { proto.RegisterFile("stats/log.proto", fileDescriptor_be815d6cfeb20831) }

var fileDescriptor_be815d6cfeb20831 = []byte{
	// 459 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x90, 0xd1, 0x8e, 0x93, 0x40,
	0x14, 0x86, 0xa5, 0xb5, 0x6c, 0x7b, 0xd8, 0xb6, 0xb3, 0xe3, 0x4d, 0xbd, 0xb2, 0x62, 0x62, 0x1a,
	0x63, 0x68, 0x52, 0x6f, 0xf4, 0xca, 0xb0, 0xcc, 0x54, 0xc9, 0xd6, 0x81, 0x0c, 0x10, 0x13, 0x4d,
	0x6c, 0x58, 0x20, 0x75, 0x62, 0x17, 0x08, 0xd0, 0x7d, 0x0d, 0x1f, 0xc2, 0x57, 0xf1, 0xc1, 0x0c,
	0x53, 0xb6, 0xd6, 0x6d, 0xe4, 0x6a, 0x2f, 0xff, 0x73, 0xbe, 0xff, 0xfc, 0x27, 0x3f, 0x8c, 0xcb,
	0x2a, 0xac, 0xca, 0xf9, 0x36, 0xdb, 0x18, 0x79, 0x91, 0x55, 0x19, 0x7e, 0x2a, 0x32, 0xa3, 0xcc,
	0x45, 0x9a, 0x86, 0x3f, 0x92, 0x62, 0x3f, 0x2b, 0x0d, 0x09, 0xe9, 0x31, 0xf4, 0xe8, 0x6d, 0x92,
	0x56, 0xf8, 0x2b, 0xe0, 0x03, 0xb2, 0x16, 0x69, 0x59, 0x85, 0x69, 0x94, 0x4c, 0x94, 0xa9, 0x32,
	0xd3, 0x16, 0xaf, 0x8d, 0xff, 0x1e, 0x30, 0xbc, 0xbb, 0xb1, 0xdd, 0x78, 0xf8, 0x45, 0x79, 0x7f,
	0xa4, 0xdf, 0xc0, 0xc5, 0x09, 0x87, 0x47, 0xd0, 0x11, 0xb1, 0x4c, 0x18, 0xf0, 0x8e, 0x88, 0xf1,
	0x47, 0xd0, 0xc2, 0x3c, 0xdf, 0x8a, 0x28, 0xac, 0x44, 0x96, 0x4e, 0x3a, 0x32, 0xfa, 0x65, 0x4b,
	0xb4, 0xf9, 0x97, 0xe6, 0xc7, 0x56, 0xfd, 0x1b, 0x68, 0x47, 0xbb, 0x93, 0xa0, 0xf7, 0xd0, 0xcf,
	0x45, 0x9e, 0x6c, 0x45, 0x9a, 0x34, 0x29, 0x2f, 0x5a, 0x52, 0xdc, 0x06, 0xe5, 0x07, 0x93, 0xfe,
	0x53, 0x81, 0xfe, 0xdd, 0xf8, 0xe4, 0xfa, 0x3b, 0x50, 0x6b, 0xe3, 0xae, 0x94, 0xb7, 0x47, 0x8b,
	0xe7, 0x6d, 0xe5, 0x49, 0x90, 0x37, 0x06, 0xfc, 0x56, 0x5a, 0x37, 0x49, 0x39, 0xe9, 0x4e, 0xbb,
	0x33, 0x6d, 0x31, 0x6d, 0xb7, 0x6e, 0x12, 0xde, 0xf0, 0xfa, 0x2f, 0x05, 0x7a, 0x72, 0xf2, 0x90,
	0xef, 0x38, 0x30, 0x8a, 0xb6, 0xd9, 0x2e, 0x5e, 0xe7, 0x45, 0x76, 0x2b, 0xe2, 0xa4, 0x98, 0x74,
	0x65, 0x5b, 0xb3, 0x96, 0x13, 0x56, 0x6d, 0x70, 0x1b, 0x9e, 0x0f, 0xa3, 0x63, 0xa9, 0x3f, 0x83,
	0xe1, 0x3f, 0xfb, 0xfb, 0xcf, 0xbe, 0xfa, 0xad, 0x80, 0xba, 0x7f, 0x02, 0x6b, 0x70, 0x16, 0xb0,
	0x2b, 0xe6, 0x7c, 0x66, 0xe8, 0x11, 0x1e, 0x83, 0xc6, 0x1c, 0x7f, 0xed, 0xf9, 0x26, 0xf7, 0x29,
	0x41, 0x4a, 0xbd, 0xe5, 0x01, 0x63, 0x36, 0xfb, 0x80, 0x3a, 0x18, 0x40, 0x75, 0xcd, 0xc0, 0xa3,
	0x04, 0x75, 0xf1, 0x10, 0x06, 0x5e, 0xe0, 0xb9, 0x94, 0x11, 0x4a, 0xd0, 0xe3, 0xbd, 0xb4, 0x2c,
	0x4a, 0x6b, 0xd9, 0xc3, 0x4f, 0x60, 0xbc, 0x34, 0xed, 0x15, 0x25, 0x6b, 0xcb, 0x61, 0xbe, 0xcd,
	0x02, 0x8a, 0x54, 0x7c, 0x0e, 0x7d, 0x9f, 0xf2, 0x4f, 0x36, 0x33, 0x57, 0xe8, 0xac, 0x56, 0x96,
	0xc9, 0x2c, 0xba, 0xa2, 0x04, 0xf5, 0x6b, 0xc5, 0x29, 0xb1, 0x39, 0xb5, 0x7c, 0x34, 0xa8, 0x53,
	0x3d, 0xdf, 0x71, 0x5d, 0x4a, 0x10, 0x48, 0x71, 0x65, 0x4b, 0xa1, 0xd5, 0xdc, 0x65, 0xb0, 0x5c,
	0x52, 0x4e, 0x09, 0x3a, 0xbf, 0xd4, 0xbf, 0x4c, 0x37, 0xa2, 0xfa, 0xbe, 0xbb, 0x36, 0xa2, 0xec,
	0x66, 0x7e, 0x68, 0x6a, 0x2e, 0x9b, 0x9a, 0xcb, 0xa2, 0xae, 0x55, 0x29, 0xde, 0xfc, 0x09, 0x00,
	0x00, 0xff, 0xff, 0x19, 0x7f, 0x95, 0xd5, 0xad, 0x03, 0x00, 0x00,
}
